### ISSUE TITLE
Raspberry Pi 4 Raspian OS (Legacy)

### ISSUE THREAD

**Issue by jcarolinares** [naclander/Calibre-Remarkable-Device-Driver-Plugin#12]
Hello, first of all thank you so much for your work here. The plugin seems to be pretty cool.

I've tried to load the plugin in my Calibre running on a Raspberry pi 4 and it was not possible:

`calibre, version 3.39.1
ERROR: Excepción no considerada: <b>SyntaxError</b>:invalid syntax (calibre_plugins.remarkable_plugin.__init__, line 53)

calibre 3.39.1  embedded-python: False is64bit: False
Linux-5.10.63-v7l+-armv7l-with-debian-10.11 Linux ('32bit', 'ELF')
('Linux', '5.10.63-v7l+', '#1496 SMP Wed Dec 1 15:58:56 GMT 2021')
Python 2.7.16
Linux: ('debian', '10.11', '')
Interface language: es
Traceback (most recent call last):
  File "/usr/lib/calibre/calibre/gui2/preferences/plugins.py", line 317, in add_plugin
    plugin = add_plugin(path)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 472, in add_plugin
    plugin = load_plugin(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/ui.py", line 61, in load_plugin
    return loader.load(path_to_zip_file)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 202, in load
    m = importlib.import_module(plugin_module)
  File "/usr/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/usr/lib/calibre/calibre/customize/zipplugin.py", line 180, in load_module
    import_name), 'exec', dont_inherit=True)
  File "calibre_plugins.remarkable_plugin.__init__", line 53
    print(f"Trying to connect to {self.remarkable_ip}")
                                                     ^
SyntaxError: invalid syntax
`

I don't know if the problem is the python version that Calibre is using or something else, any hint please?

**Comment by naclander** [comment]
That specific problem you're seeing is happening because you're using `python2` where `print` is not a function.

However, even if you try and run this with python3 the plugin is still not going to work. It relies on python c extensions and Calibre doesn't make it easy to distribute these. So currently the plugin only really works on other x86 Linux machines.

**Comment by jcarolinares** [comment]
That's sad! but it does not have any sense to try to solve it here. I will wait until the new Raspbian OS versions and Calibre will be compatible between them and using Python3. 

Thanks!
