### ISSUE TITLE
'RemarkablePlugin' object has no attribute 'seen_device'

### ISSUE THREAD

**Issue by pb6854** [naclander/Calibre-Remarkable-Device-Driver-Plugin#13]
Hi,

I get the error message above in the debug log when starting calibre-debug -g with  Python 3.8.10 and calibre 5.37. I tried installing the plugin  from the zip and from the cloned development folder. The plugin is configured correctly but it doesn't seem to even get to the point of connecting to the device. Any clue is highly appreciated...

thx,

Peter

**Comment by naclander** [comment]
Looks like the same error as here: https://github.com/naclander/Calibre-Remarkable-Device-Driver-Plugin/issues/5

Lets keep the discussion on #5, since I think its the same error.
