### ISSUE TITLE
How do you use it?

### ISSUE THREAD

**Issue by hkdd** [naclander/Calibre-Remarkable-Device-Driver-Plugin#4]
The usage instructions just say:

>Once the plugin is installed and configured

Anyone know how to actually use it once installed?  Also, installing 1.2.0 lists the plugin version as 1.1.0 in the plugins interface.

**Comment by naclander** [comment]
Hey, thanks for noticing that. I forgot to fill that section in. I'll fill out the README in another PR.

**Comment by naclander** [comment]
I've updated the Usage section. I'm going to resolve this issue, but please let me know if everything worked for you, or feel free to open another issue if you face another problem.
