### ISSUE TITLE
Please Help I have no Idea What I am doing

### ISSUE THREAD

**Issue by PleaseHelpMeImLost** [naclander/Calibre-Remarkable-Device-Driver-Plugin#8]
I have scoured the internet and do not understand the bulk of this. I have established an SSH connection with my reMarkable. I have downloaded the Zip folder and gone to the plugin interface on Calibre. I then click "Load plugin from file" and select the zipped folder to install. The requisite response from Calibre is, "The plugin in 'zipped folder name' is invalid. It does not contain a top-level __init__.py file. Obviously, I can see that file in the zip folder from download so I do not understand why it is not cooperating. I attempted your developer instructions but because this is literally my first trip into the command prompt function of my computer and I have never done something like this I am totally lost. Am I messed up, screwed, or is there an easy fix? Thanks for your help and apologies for the incompetence.

**Comment by naclander** [comment]
I think your problem is generally about installing plugins in Calibre, and not specific to this plugin. 

Please make sure you can install other plugins. You can follow this guide:
https://www.ereader-palace.com/install-plugins-calibre/
