### ISSUE TITLE
 ImportError: cannot import name 'asn1' from 'cryptography.hazmat.bindings._rust' (unknown location)

### ISSUE THREAD

**Issue by tak-21** [naclander/Calibre-Remarkable-Device-Driver-Plugin#9]
Hi, as advised, here is the error in a seperat topic.

    ImportError: cannot import name 'asn1' from 'cryptography.hazmat.bindings._rust' (unknown location)

You said, that it is not so easy possible to create a portable plugin due to remarkable_fs dependencie's relying on c bindings.
Well ... all I hear is: there is a more complicated way to do it but it will work. (Sorry I am not a developer, just a user so please forgive me if my view is naive!) 
Can you please - as in: please, please, please ;) - share this more complicated way? 

I would really love to use your plugin to sync books with my remarkable 2 :)

**Comment by naclander** [comment]
What I meant was that I currently do not know how to make it work. I would love for someone to contribute a patch to make this work across different OSes and architectures.
